apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: example-app
  endpoints:
    - port: web
      interval: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
          targetLabel: region
